const processors2 = [
  {
    "category": "Category",
    "manufacturer": "Manufacturer",
    "model": "Model",
    "release_year": "Release_Year",
    "cpu_architecture": "Architecture",
    "cpu_cores": "Cores",
    "cpu_threads": "Threads",
    "base_clock_ghz": "Base_Clock_GHz",
    "max_cpu_clock_ghz": "Boost_Clock_GHz",
    "process_node_nm": "Process_nm",
    "tdp_w": "TDP_W",
    "cache_mb": "Cache_MB",
    "gpu": "GPU_Integrated"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-14900HX",
    "release_year": "2024",
    "cpu_architecture": "Raptor Lake Refresh",
    "cpu_cores": "24",
    "cpu_threads": "32",
    "base_clock_ghz": "2.2",
    "max_cpu_clock_ghz": "5.8",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "68",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-14900H",
    "release_year": "2024",
    "cpu_architecture": "Raptor Lake Refresh",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "5.7",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-13980HX",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "24",
    "cpu_threads": "32",
    "base_clock_ghz": "2.2",
    "max_cpu_clock_ghz": "5.6",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "36",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-13900HX",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "24",
    "cpu_threads": "32",
    "base_clock_ghz": "2.2",
    "max_cpu_clock_ghz": "5.5",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "36",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-13900H",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "5.4",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-12950HX",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "16",
    "cpu_threads": "24",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "30",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-12900HX",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "16",
    "cpu_threads": "24",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "30",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-12900HK",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-12900H",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-11980HK",
    "release_year": "2021",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "65",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-11900H",
    "release_year": "2021",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.9",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-10980HK",
    "release_year": "2020",
    "cpu_architecture": "Comet Lake",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "5.3",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-10885H",
    "release_year": "2020",
    "cpu_architecture": "Comet Lake",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "5.3",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-9980HK",
    "release_year": "2019",
    "cpu_architecture": "Coffee Lake Refresh",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-9880H",
    "release_year": "2019",
    "cpu_architecture": "Coffee Lake Refresh",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-8950HK",
    "release_year": "2018",
    "cpu_architecture": "Coffee Lake",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-8850H",
    "release_year": "2018",
    "cpu_architecture": "Coffee Lake",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "4.3",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "9",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-14700HX",
    "release_year": "2024",
    "cpu_architecture": "Raptor Lake Refresh",
    "cpu_cores": "20",
    "cpu_threads": "28",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "5.5",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "48",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-14700H",
    "release_year": "2024",
    "cpu_architecture": "Raptor Lake Refresh",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "5.5",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-14650HX",
    "release_year": "2024",
    "cpu_architecture": "Raptor Lake Refresh",
    "cpu_cores": "16",
    "cpu_threads": "24",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "30",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-13700HX",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "16",
    "cpu_threads": "24",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "30",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-13700H",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-12800HX",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "16",
    "cpu_threads": "24",
    "base_clock_ghz": "2.0",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "25",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-12700H",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.7",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-11800H",
    "release_year": "2021",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-10875H",
    "release_year": "2020",
    "cpu_architecture": "Comet Lake",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "5.1",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-10750H",
    "release_year": "2020",
    "cpu_architecture": "Comet Lake",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-9850H",
    "release_year": "2019",
    "cpu_architecture": "Coffee Lake Refresh",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-9750H",
    "release_year": "2019",
    "cpu_architecture": "Coffee Lake Refresh",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-8850H",
    "release_year": "2018",
    "cpu_architecture": "Coffee Lake",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "4.3",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "9",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-8750H",
    "release_year": "2018",
    "cpu_architecture": "Coffee Lake",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.2",
    "max_cpu_clock_ghz": "4.1",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "9",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-7820HK",
    "release_year": "2017",
    "cpu_architecture": "Kaby Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "3.9",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-7700HQ",
    "release_year": "2017",
    "cpu_architecture": "Kaby Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.8",
    "max_cpu_clock_ghz": "3.8",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "6",
    "gpu": "Intel HD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-6820HK",
    "release_year": "2015",
    "cpu_architecture": "Skylake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "3.6",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 530"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-6700HQ",
    "release_year": "2015",
    "cpu_architecture": "Skylake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "3.5",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "6",
    "gpu": "Intel HD Graphics 530"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-4940MX",
    "release_year": "2014",
    "cpu_architecture": "Haswell",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "3.1",
    "max_cpu_clock_ghz": "4.0",
    "process_node_nm": "22",
    "tdp_w": "57",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 4600"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-4910MQ",
    "release_year": "2014",
    "cpu_architecture": "Haswell",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "3.9",
    "process_node_nm": "22",
    "tdp_w": "47",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 4600"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-4810MQ",
    "release_year": "2014",
    "cpu_architecture": "Haswell",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.8",
    "max_cpu_clock_ghz": "3.8",
    "process_node_nm": "22",
    "tdp_w": "47",
    "cache_mb": "6",
    "gpu": "Intel HD Graphics 4600"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-4800MQ",
    "release_year": "2013",
    "cpu_architecture": "Haswell",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "22",
    "tdp_w": "47",
    "cache_mb": "6",
    "gpu": "Intel HD Graphics 4600"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-3940XM",
    "release_year": "2013",
    "cpu_architecture": "Ivy Bridge",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "3.9",
    "process_node_nm": "22",
    "tdp_w": "55",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 4000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-3840QM",
    "release_year": "2013",
    "cpu_architecture": "Ivy Bridge",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.8",
    "max_cpu_clock_ghz": "3.8",
    "process_node_nm": "22",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 4000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-3820QM",
    "release_year": "2012",
    "cpu_architecture": "Ivy Bridge",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "22",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 4000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-2960XM",
    "release_year": "2011",
    "cpu_architecture": "Sandy Bridge",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "32",
    "tdp_w": "55",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 3000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-2860QM",
    "release_year": "2011",
    "cpu_architecture": "Sandy Bridge",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "3.6",
    "process_node_nm": "32",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 3000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-2820QM",
    "release_year": "2011",
    "cpu_architecture": "Sandy Bridge",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "3.4",
    "process_node_nm": "32",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel HD Graphics 3000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-14500H",
    "release_year": "2024",
    "cpu_architecture": "Raptor Lake Refresh",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.9",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "20",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-13500H",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "4.7",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "18",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-12600HX",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "10",
    "tdp_w": "55",
    "cache_mb": "18",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-12500H",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "18",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-11500H",
    "release_year": "2021",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-11400H",
    "release_year": "2021",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-10500H",
    "release_year": "2020",
    "cpu_architecture": "Comet Lake",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-10300H",
    "release_year": "2020",
    "cpu_architecture": "Comet Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-9400H",
    "release_year": "2019",
    "cpu_architecture": "Coffee Lake Refresh",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.3",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-9300H",
    "release_year": "2019",
    "cpu_architecture": "Coffee Lake Refresh",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "4.1",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-8400H",
    "release_year": "2018",
    "cpu_architecture": "Coffee Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-8300H",
    "release_year": "2018",
    "cpu_architecture": "Coffee Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.0",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "8",
    "gpu": "Intel UHD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-7440HQ",
    "release_year": "2017",
    "cpu_architecture": "Kaby Lake",
    "cpu_cores": "4",
    "cpu_threads": "4",
    "base_clock_ghz": "2.8",
    "max_cpu_clock_ghz": "3.8",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "6",
    "gpu": "Intel HD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-7300HQ",
    "release_year": "2017",
    "cpu_architecture": "Kaby Lake",
    "cpu_cores": "4",
    "cpu_threads": "4",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "3.5",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "6",
    "gpu": "Intel HD Graphics 630"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-6440HQ",
    "release_year": "2015",
    "cpu_architecture": "Skylake",
    "cpu_cores": "4",
    "cpu_threads": "4",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "3.5",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "6",
    "gpu": "Intel HD Graphics 530"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-6300HQ",
    "release_year": "2015",
    "cpu_architecture": "Skylake",
    "cpu_cores": "4",
    "cpu_threads": "4",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "3.2",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "6",
    "gpu": "Intel HD Graphics 530"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-4340M",
    "release_year": "2014",
    "cpu_architecture": "Haswell",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "3.6",
    "process_node_nm": "22",
    "tdp_w": "37",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4600"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-4310M",
    "release_year": "2014",
    "cpu_architecture": "Haswell",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "3.4",
    "process_node_nm": "22",
    "tdp_w": "37",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4600"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-4300M",
    "release_year": "2013",
    "cpu_architecture": "Haswell",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "3.3",
    "process_node_nm": "22",
    "tdp_w": "37",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4600"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-3380M",
    "release_year": "2013",
    "cpu_architecture": "Ivy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "3.6",
    "process_node_nm": "22",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-3360M",
    "release_year": "2012",
    "cpu_architecture": "Ivy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.8",
    "max_cpu_clock_ghz": "3.5",
    "process_node_nm": "22",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-3320M",
    "release_year": "2012",
    "cpu_architecture": "Ivy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "3.3",
    "process_node_nm": "22",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-2540M",
    "release_year": "2011",
    "cpu_architecture": "Sandy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "3.3",
    "process_node_nm": "32",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 3000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-2520M",
    "release_year": "2011",
    "cpu_architecture": "Sandy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "3.2",
    "process_node_nm": "32",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 3000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-13100H",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "10",
    "cpu_threads": "12",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-12300H",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "8",
    "cpu_threads": "12",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-11300H",
    "release_year": "2021",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "3.1",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "10",
    "tdp_w": "35",
    "cache_mb": "8",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-10110U",
    "release_year": "2019",
    "cpu_architecture": "Comet Lake",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "4.1",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "4",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-8145U",
    "release_year": "2018",
    "cpu_architecture": "Whiskey Lake",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "3.9",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "4",
    "gpu": "Intel UHD Graphics 620"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-8130U",
    "release_year": "2018",
    "cpu_architecture": "Kaby Lake Refresh",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.2",
    "max_cpu_clock_ghz": "3.4",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "4",
    "gpu": "Intel UHD Graphics 620"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-7130U",
    "release_year": "2017",
    "cpu_architecture": "Kaby Lake",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "2.7",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 620"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-7100U",
    "release_year": "2016",
    "cpu_architecture": "Kaby Lake",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "2.4",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 620"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-6100H",
    "release_year": "2015",
    "cpu_architecture": "Skylake",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "2.7",
    "process_node_nm": "14",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 530"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-6100U",
    "release_year": "2015",
    "cpu_architecture": "Skylake",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "2.3",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 520"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-5010U",
    "release_year": "2015",
    "cpu_architecture": "Broadwell",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "2.1",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 5500"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-4030U",
    "release_year": "2014",
    "cpu_architecture": "Haswell",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "1.9",
    "max_cpu_clock_ghz": "1.9",
    "process_node_nm": "22",
    "tdp_w": "15",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4400"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-4000M",
    "release_year": "2013",
    "cpu_architecture": "Haswell",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "2.4",
    "process_node_nm": "22",
    "tdp_w": "37",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4600"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-3130M",
    "release_year": "2013",
    "cpu_architecture": "Ivy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "2.6",
    "process_node_nm": "22",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-3120M",
    "release_year": "2012",
    "cpu_architecture": "Ivy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "2.5",
    "process_node_nm": "22",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 4000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-2370M",
    "release_year": "2012",
    "cpu_architecture": "Sandy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "2.4",
    "process_node_nm": "32",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 3000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-2350M",
    "release_year": "2011",
    "cpu_architecture": "Sandy Bridge",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "2.3",
    "process_node_nm": "32",
    "tdp_w": "35",
    "cache_mb": "3",
    "gpu": "Intel HD Graphics 3000"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i9-13900H",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "5.4",
    "process_node_nm": "10",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1370P",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "1.9",
    "max_cpu_clock_ghz": "5.2",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1360P",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "2.2",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "18",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1340P",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "1.9",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "18",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1340P",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "1.9",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "18",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-1315U",
    "release_year": "2023",
    "cpu_architecture": "Raptor Lake",
    "cpu_cores": "6",
    "cpu_threads": "8",
    "base_clock_ghz": "1.2",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "10",
    "tdp_w": "15",
    "cache_mb": "10",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1280P",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "14",
    "cpu_threads": "20",
    "base_clock_ghz": "1.8",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "24",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1270P",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "2.2",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "18",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1260P",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "4.7",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "18",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1250P",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "1.7",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1240P",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "12",
    "cpu_threads": "16",
    "base_clock_ghz": "1.7",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-1215U",
    "release_year": "2022",
    "cpu_architecture": "Alder Lake",
    "cpu_cores": "6",
    "cpu_threads": "8",
    "base_clock_ghz": "1.2",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "10",
    "tdp_w": "15",
    "cache_mb": "10",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1195G7",
    "release_year": "2021",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1185G7",
    "release_year": "2020",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1165G7",
    "release_year": "2020",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.8",
    "max_cpu_clock_ghz": "4.7",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "12",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1155G7",
    "release_year": "2021",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "8",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1145G7",
    "release_year": "2020",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.6",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "8",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1135G7",
    "release_year": "2020",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.4",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "8",
    "gpu": "Intel Iris Xe"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-1125G4",
    "release_year": "2020",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.0",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "8",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-1115G4",
    "release_year": "2020",
    "cpu_architecture": "Tiger Lake",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "4.1",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "6",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1068NG7",
    "release_year": "2020",
    "cpu_architecture": "Ice Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.1",
    "process_node_nm": "10",
    "tdp_w": "28",
    "cache_mb": "8",
    "gpu": "Intel Iris Plus"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-1065G7",
    "release_year": "2019",
    "cpu_architecture": "Ice Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "1.3",
    "max_cpu_clock_ghz": "3.9",
    "process_node_nm": "10",
    "tdp_w": "15",
    "cache_mb": "8",
    "gpu": "Intel Iris Plus"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1035G7",
    "release_year": "2019",
    "cpu_architecture": "Ice Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "1.2",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "10",
    "tdp_w": "15",
    "cache_mb": "6",
    "gpu": "Intel Iris Plus"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1035G4",
    "release_year": "2019",
    "cpu_architecture": "Ice Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "1.1",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "10",
    "tdp_w": "15",
    "cache_mb": "6",
    "gpu": "Intel Iris Plus"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-1035G1",
    "release_year": "2019",
    "cpu_architecture": "Ice Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "1.0",
    "max_cpu_clock_ghz": "3.6",
    "process_node_nm": "10",
    "tdp_w": "15",
    "cache_mb": "6",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i3-1005G1",
    "release_year": "2019",
    "cpu_architecture": "Ice Lake",
    "cpu_cores": "2",
    "cpu_threads": "4",
    "base_clock_ghz": "1.2",
    "max_cpu_clock_ghz": "3.4",
    "process_node_nm": "10",
    "tdp_w": "15",
    "cache_mb": "4",
    "gpu": "Intel UHD Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-8665U",
    "release_year": "2019",
    "cpu_architecture": "Whiskey Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "1.9",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "8",
    "gpu": "Intel UHD Graphics 620"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i7-8565U",
    "release_year": "2018",
    "cpu_architecture": "Whiskey Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "1.8",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "8",
    "gpu": "Intel UHD Graphics 620"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-8365U",
    "release_year": "2019",
    "cpu_architecture": "Whiskey Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "1.6",
    "max_cpu_clock_ghz": "4.1",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "6",
    "gpu": "Intel UHD Graphics 620"
  },
  {
    "category": "Laptop",
    "manufacturer": "Intel",
    "model": "Core i5-8265U",
    "release_year": "2018",
    "cpu_architecture": "Whiskey Lake",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "1.6",
    "max_cpu_clock_ghz": "3.9",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "6",
    "gpu": "Intel UHD Graphics 620"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 8945HS",
    "release_year": "2024",
    "cpu_architecture": "Zen 5",
    "cpu_cores": "12",
    "cpu_threads": "24",
    "base_clock_ghz": "4.0",
    "max_cpu_clock_ghz": "5.5",
    "process_node_nm": "4",
    "tdp_w": "45",
    "cache_mb": "32",
    "gpu": "AMD Radeon 870M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 8945HX",
    "release_year": "2024",
    "cpu_architecture": "Zen 5",
    "cpu_cores": "16",
    "cpu_threads": "32",
    "base_clock_ghz": "3.5",
    "max_cpu_clock_ghz": "5.6",
    "process_node_nm": "4",
    "tdp_w": "55",
    "cache_mb": "80",
    "gpu": "AMD Radeon 890M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 7945HX3D",
    "release_year": "2023",
    "cpu_architecture": "Zen 4",
    "cpu_cores": "16",
    "cpu_threads": "32",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "5.4",
    "process_node_nm": "5",
    "tdp_w": "55",
    "cache_mb": "144",
    "gpu": "AMD Radeon 780M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 7945HX",
    "release_year": "2023",
    "cpu_architecture": "Zen 4",
    "cpu_cores": "16",
    "cpu_threads": "32",
    "base_clock_ghz": "2.5",
    "max_cpu_clock_ghz": "5.4",
    "process_node_nm": "5",
    "tdp_w": "55",
    "cache_mb": "80",
    "gpu": "AMD Radeon 780M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 7940HS",
    "release_year": "2023",
    "cpu_architecture": "Zen 4",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "4.0",
    "max_cpu_clock_ghz": "5.2",
    "process_node_nm": "5",
    "tdp_w": "35",
    "cache_mb": "16",
    "gpu": "AMD Radeon 780M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 6980HX",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "6",
    "tdp_w": "45",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 6900HX",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.9",
    "process_node_nm": "6",
    "tdp_w": "45",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 6900HS",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.9",
    "process_node_nm": "6",
    "tdp_w": "35",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 5980HX",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "7",
    "tdp_w": "45",
    "cache_mb": "20",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 5980HS",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "4.8",
    "process_node_nm": "7",
    "tdp_w": "35",
    "cache_mb": "20",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 5900HX",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "7",
    "tdp_w": "45",
    "cache_mb": "20",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 5900HS",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "4.6",
    "process_node_nm": "7",
    "tdp_w": "35",
    "cache_mb": "20",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 4900H",
    "release_year": "2020",
    "cpu_architecture": "Zen 2",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "7",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 9 4900HS",
    "release_year": "2020",
    "cpu_architecture": "Zen 2",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "4.3",
    "process_node_nm": "7",
    "tdp_w": "35",
    "cache_mb": "12",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 8840HS",
    "release_year": "2024",
    "cpu_architecture": "Zen 5",
    "cpu_cores": "10",
    "cpu_threads": "20",
    "base_clock_ghz": "3.8",
    "max_cpu_clock_ghz": "5.3",
    "process_node_nm": "4",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "AMD Radeon 870M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 8840H",
    "release_year": "2024",
    "cpu_architecture": "Zen 5",
    "cpu_cores": "10",
    "cpu_threads": "20",
    "base_clock_ghz": "3.8",
    "max_cpu_clock_ghz": "5.3",
    "process_node_nm": "4",
    "tdp_w": "45",
    "cache_mb": "24",
    "gpu": "AMD Radeon 870M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 7840HS",
    "release_year": "2023",
    "cpu_architecture": "Zen 4",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.8",
    "max_cpu_clock_ghz": "5.1",
    "process_node_nm": "5",
    "tdp_w": "35",
    "cache_mb": "16",
    "gpu": "AMD Radeon 780M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 7840H",
    "release_year": "2023",
    "cpu_architecture": "Zen 4",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.8",
    "max_cpu_clock_ghz": "5.1",
    "process_node_nm": "5",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "AMD Radeon 780M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 7735HS",
    "release_year": "2023",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.2",
    "max_cpu_clock_ghz": "4.75",
    "process_node_nm": "6",
    "tdp_w": "35",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 7735H",
    "release_year": "2023",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.2",
    "max_cpu_clock_ghz": "4.75",
    "process_node_nm": "6",
    "tdp_w": "45",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 7735U",
    "release_year": "2023",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "4.7",
    "process_node_nm": "6",
    "tdp_w": "15",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 6800H",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.2",
    "max_cpu_clock_ghz": "4.7",
    "process_node_nm": "6",
    "tdp_w": "45",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 6800HS",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.2",
    "max_cpu_clock_ghz": "4.7",
    "process_node_nm": "6",
    "tdp_w": "35",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 6800U",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.7",
    "max_cpu_clock_ghz": "4.7",
    "process_node_nm": "6",
    "tdp_w": "15",
    "cache_mb": "20",
    "gpu": "AMD Radeon 680M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 5800H",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.2",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "7",
    "tdp_w": "45",
    "cache_mb": "20",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 5800HS",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.8",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "7",
    "tdp_w": "35",
    "cache_mb": "20",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 5800U",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "1.9",
    "max_cpu_clock_ghz": "4.4",
    "process_node_nm": "7",
    "tdp_w": "15",
    "cache_mb": "20",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 4800H",
    "release_year": "2020",
    "cpu_architecture": "Zen 2",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "7",
    "tdp_w": "45",
    "cache_mb": "12",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 4800HS",
    "release_year": "2020",
    "cpu_architecture": "Zen 2",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "7",
    "tdp_w": "35",
    "cache_mb": "12",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 4800U",
    "release_year": "2020",
    "cpu_architecture": "Zen 2",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "1.8",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "7",
    "tdp_w": "15",
    "cache_mb": "12",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 3750H",
    "release_year": "2019",
    "cpu_architecture": "Zen+",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.0",
    "process_node_nm": "12",
    "tdp_w": "35",
    "cache_mb": "6",
    "gpu": "AMD Radeon Vega 10"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 3700U",
    "release_year": "2019",
    "cpu_architecture": "Zen+",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.0",
    "process_node_nm": "12",
    "tdp_w": "15",
    "cache_mb": "6",
    "gpu": "AMD Radeon Vega 10"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 2800H",
    "release_year": "2018",
    "cpu_architecture": "Zen",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "3.8",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "4",
    "gpu": "AMD Radeon Vega 11"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 7 2700U",
    "release_year": "2017",
    "cpu_architecture": "Zen",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.2",
    "max_cpu_clock_ghz": "3.8",
    "process_node_nm": "14",
    "tdp_w": "15",
    "cache_mb": "4",
    "gpu": "AMD Radeon Vega 10"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 8640HS",
    "release_year": "2024",
    "cpu_architecture": "Zen 5",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.5",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "4",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "AMD Radeon 860M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 8640H",
    "release_year": "2024",
    "cpu_architecture": "Zen 5",
    "cpu_cores": "8",
    "cpu_threads": "16",
    "base_clock_ghz": "3.5",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "4",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "AMD Radeon 860M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 7640HS",
    "release_year": "2023",
    "cpu_architecture": "Zen 4",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "4.3",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "5",
    "tdp_w": "35",
    "cache_mb": "16",
    "gpu": "AMD Radeon 760M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 7640H",
    "release_year": "2023",
    "cpu_architecture": "Zen 4",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "4.3",
    "max_cpu_clock_ghz": "5.0",
    "process_node_nm": "5",
    "tdp_w": "45",
    "cache_mb": "16",
    "gpu": "AMD Radeon 760M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 7535HS",
    "release_year": "2023",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.55",
    "process_node_nm": "6",
    "tdp_w": "35",
    "cache_mb": "19",
    "gpu": "AMD Radeon 660M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 7535H",
    "release_year": "2023",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.55",
    "process_node_nm": "6",
    "tdp_w": "45",
    "cache_mb": "19",
    "gpu": "AMD Radeon 660M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 7535U",
    "release_year": "2023",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "6",
    "tdp_w": "15",
    "cache_mb": "19",
    "gpu": "AMD Radeon 660M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 6600H",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "6",
    "tdp_w": "45",
    "cache_mb": "19",
    "gpu": "AMD Radeon 660M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 6600HS",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "6",
    "tdp_w": "35",
    "cache_mb": "19",
    "gpu": "AMD Radeon 660M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 6600U",
    "release_year": "2022",
    "cpu_architecture": "Zen 3+",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.9",
    "max_cpu_clock_ghz": "4.5",
    "process_node_nm": "6",
    "tdp_w": "15",
    "cache_mb": "19",
    "gpu": "AMD Radeon 660M"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 5600H",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "3.3",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "7",
    "tdp_w": "45",
    "cache_mb": "19",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 5600HS",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "7",
    "tdp_w": "35",
    "cache_mb": "19",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 5600U",
    "release_year": "2021",
    "cpu_architecture": "Zen 3",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.3",
    "max_cpu_clock_ghz": "4.2",
    "process_node_nm": "7",
    "tdp_w": "15",
    "cache_mb": "19",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 4600H",
    "release_year": "2020",
    "cpu_architecture": "Zen 2",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "4.0",
    "process_node_nm": "7",
    "tdp_w": "45",
    "cache_mb": "11",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 4600HS",
    "release_year": "2020",
    "cpu_architecture": "Zen 2",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "3.0",
    "max_cpu_clock_ghz": "4.0",
    "process_node_nm": "7",
    "tdp_w": "35",
    "cache_mb": "11",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 4600U",
    "release_year": "2020",
    "cpu_architecture": "Zen 2",
    "cpu_cores": "6",
    "cpu_threads": "12",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "4.0",
    "process_node_nm": "7",
    "tdp_w": "15",
    "cache_mb": "11",
    "gpu": "AMD Radeon Graphics"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 3580U",
    "release_year": "2019",
    "cpu_architecture": "Zen+",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "12",
    "tdp_w": "15",
    "cache_mb": "6",
    "gpu": "AMD Radeon Vega 9"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 3550H",
    "release_year": "2019",
    "cpu_architecture": "Zen+",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "12",
    "tdp_w": "35",
    "cache_mb": "6",
    "gpu": "AMD Radeon Vega 8"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 3500U",
    "release_year": "2019",
    "cpu_architecture": "Zen+",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "2.1",
    "max_cpu_clock_ghz": "3.7",
    "process_node_nm": "12",
    "tdp_w": "15",
    "cache_mb": "6",
    "gpu": "AMD Radeon Vega 8"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 2600H",
    "release_year": "2018",
    "cpu_architecture": "Zen",
    "cpu_cores": "4",
    "cpu_threads": "8",
    "base_clock_ghz": "3.2",
    "max_cpu_clock_ghz": "3.6",
    "process_node_nm": "14",
    "tdp_w": "45",
    "cache_mb": "4",
    "gpu": "AMD Radeon Vega 8"
  },
  {
    "category": "Laptop",
    "manufacturer": "AMD",
    "model": "Ryzen 5 2500U",
    "release_year": "",
    "cpu_architecture": "",
    "cpu_cores": "",
    "cpu_threads": "",
    "base_clock_ghz": "",
    "max_cpu_clock_ghz": "",
    "process_node_nm": "",
    "tdp_w": "",
    "cache_mb": "",
    "gpu": ""
  }
];